services:
  postgres:
    image: postgres:15-alpine
    container_name: saas_auth_db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: jXZteWj5b17n
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authuser -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: auth_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
      SPRING_DATASOURCE_HOST: postgres
      SPRING_DATASOURCE_DB: authdb
      SPRING_DATASOURCE_USERNAME: authuser
      SPRING_DATASOURCE_PASSWORD: jXZteWj5b17n
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: auth_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data: